### ISSUE TITLE
Import settings error

### ISSUE THREAD

**Issue by g33xter** [codewatchorg/SideStep#1]
![screenshot from 2015-04-21 01 07 45](https://cloud.githubusercontent.com/assets/8503135/7247872/e6b3f520-e7c2-11e4-856f-64ef9da2c34a.png)

**Comment by codewatchorg** [comment]
Are you running it in Cygwin on Windows?  If so, I just pushed an update out that will correct path delimiters.  It is not supported on Linux at the moment as it requires Visual Studio.  I have been unable to get it to compile with ming-gcc and make this cross-platform compatible (remove the VS requirement).

**Comment by g33xter** [comment]
got it, I was running it on Linux. Thanks.

**Comment by codewatchorg** [comment]
Unsupported OS
